package roomescape.infrastructure.payment;

import java.util.Arrays;

/*
    Error codes from Toss API: only bypassing error codes below
    https://docs.tosspayments.com/reference/error-codes#코어-api-별-에러
 */
public enum TossStatusCode {
    ALREADY_PROCESSED_PAYMENT,
    EXCEED_MAX_CARD_INSTALLMENT_PLAN,
    NOT_ALLOWED_POINT_USE,
    INVALID_REJECT_CARD,
    BELOW_MINIMUM_AMOUNT,
    INVALID_CARD_EXPIRATION,
    INVALID_STOPPED_CARD,
    EXCEED_MAX_DAILY_PAYMENT_COUNT,
    NOT_SUPPORTED_INSTALLMENT_PLAN_CARD_OR_MERCHANT,
    INVALID_CARD_INSTALLMENT_PLAN,
    NOT_SUPPORTED_MONTHLY_INSTALLMENT_PLAN,
    EXCEED_MAX_PAYMENT_AMOUNT,
    RESTRICTED_TRANSFER_ACCOUNT,
    INVALID_CARD_NUMBER,
    INVALID_UNREGISTERED_SUBMALL,
    EXCEED_MAX_ONE_DAY_WITHDRAW_AMOUNT,
    EXCEED_MAX_ONE_TIME_WITHDRAW_AMOUNT,
    CARD_PROCESSING_ERROR,
    EXCEED_MAX_AMOUNT,
    INVALID_ACCOUNT_INFO_RE_REGISTER,
    NOT_AVAILABLE_PAYMENT,
    UNAPPROVED_ORDER_ID,
    REJECT_ACCOUNT_PAYMENT,
    REJECT_CARD_PAYMENT,
    REJECT_CARD_COMPANY,
    REJECT_TOSSPAY_INVALID_ACCOUNT,
    EXCEED_MAX_AUTH_COUNT,
    EXCEED_MAX_ONE_DAY_AMOUNT,
    NOT_AVAILABLE_BANK,
    INVALID_PASSWORD,
    FDS_ERROR,
    NOT_FOUND_PAYMENT,
    NOT_FOUND_PAYMENT_SESSION,
    FAILED_PAYMENT_INTERNAL_SYSTEM_PROCESSING,
    ;

    public static boolean isAcceptableError(String code) {
        return Arrays.stream(TossStatusCode.values())
                .anyMatch(tossStatusCode -> tossStatusCode.name().equals(code));
    }
}
