spring:
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:database

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

  sql:
    init:
      data-locations: classpath:init_data.sql

toss:
  payment:
    widget-secret-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
    base-url: https://api.tosspayments.com/v1/payments

---

spring:
  config:
    activate:
      on-profile: prod

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:database

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

  sql:
    init:
      data-locations: classpath:init_data.sql

toss:
  payment:
    widget-secret-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
    base-url: https://api.tosspayments.com/v1/payments

