spring:
  profiles:
    default: local

---

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

---

logging:
  level:
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


---

spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:database
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql


security:
  jwt:
    token:
      secret-key: Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=
      expire-length: 36000000 # 60 minutes

payment:
  toss:
    secret-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
    base-url: https://api.tosspayments.com/v1/payments/
---

spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test-database
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:test-data.sql

security:
  jwt:
    token:
      secret-key: Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=
      expire-length: 36000000 # 60 minutes

payment:
  toss:
    secret-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
    base-url: https://api.tosspayments.com/v1/payments/
