spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:database
spring.jpa.open-in-view=false
spring.sql.init.data-locations=classpath:init.sql
security.jwt.token.secret-key=asdasdjfsdfhajsdfhjshdflhsadklfjskaldjfkasdjflksajdklfj134kjkldjdkslfjk13j4sdafdfsadfasdfsadfasdfasdfsad
toss-payments.secret-key=test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
logging.level.root=INFO
# LOG_PATH
logging.file.path=logs
# LOG_FILE
logging.file.name=roomescape.log
# LOG_DATEFORMAT_PATTERN
logging.pattern.dateformat=yyyy-MM-dd HH:mm:ss
