# Database Connection
spring.datasource.url=jdbc:h2:mem:database
spring.datasource.username=root
spring.datasource.password=1234
# Database Script Setting
spring.sql.init.data-locations=classpath:/init_data.sql
# JPA Setting
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_batch_fetch_size=50
# H2 Console Setting
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# JWT Token Setting
security.jwt.token.secret-key=emN2cGdvcHdsZXcyNjIzNDEwYWthQCEjYXNkL3ZjeGtsa2x2eGNremxqMjAxNHNpZGchQFRTRE9TREFGS0x3cWxrZWprYWZhcw==
security.jwt.token.expire-length=3600000
# Toss Payment
toss_payment_base_url=https://api.tosspayments.com
toss_payment_secret_key=test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
toss_confirm_server_uri=/v1/payments/confirm
