spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:database
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.schema-locations=classpath:sql/schema.sql
spring.sql.init.data-locations=classpath:sql/data.sql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.defer-datasource-initialization=false
logging.level.root=INFO
toss.base-url=https://api.tosspayments.com/v1
toss.secret-key=${TOSS_SECRET_KEY}
jwt.secret=${JWT_SECRET}
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

