spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:database
jwt.secretKey=Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.ddl-auto=create-drop
spring.sql.init.mode=never
toss.secretKey=test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
toss.baseUrl=https://api.tosspayments.com