spring:
  profiles:
    active: prod
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:database
    username: sa
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

logging:
  level:
    root: info
    roomescape.global.LoggingInterceptor: info
  file:
    name: logs/app.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"