INSERT INTO theme (theme_name, description, thumbnail)
VALUES ('블라인드',
        '아무것도 보이지 않는... 알 수 없는 장소로 잡혀온 당신, 희미한 빛사이로 들려오는 의문의 목소리를 따라 탈출하라!',
        '/image/블라인드.jpg'),
       ('거울의방',
        '친구들과 함께 등산을 하던 중 갑자기 내려진 폭우! 날씨는 어두워지고 멀리서 보이는 한줄기 빛! 그 빛줄기를 따라가니 작은 폐허가 한채 있다.​"그래 여기서 비를 피하자" "그런데 이 음산한 분위기는 뭐지?" 사방이 거울로 둘러싸인 이 곳에서 당신은 살아남을 수 있는가?',
        '/image/거울의방.jpg'),
       ('B아파트13동1313호',
        '이야기가 끝나는 순간,공포가 현실이 된다.',
        '/image/B아파트13동1313호.png'),
       ('루시드드림',
        '현실과 구분이 되지 않는 꿈. 그 안에서 당신은 처음보는 소녀의 부름에 낯선 방에 이르게 된다. 자신을 J라 소개하는 그녀 J는 자신의 이야기를 들어달라 해놓고는 홀연히 사려져버린다. "J...? 4년 전 연쇄실종사건의 마지막 실종자...J?" 단순한 꿈이 아님을 직감적으로 눈치챈 당신은 천천히 방을 둘러보게 되는데....',
        '/image/루시드드림.jpg'),
       ('꽁노리',
        '이따 병후니랑 지후니랑 꽁을 차기로 햇따.',
        '/image/꽁노리.jpg'),
       ('엑스튜브',
        '당신은 X튜브를 운영하는 BJ이다. 각종 음식과 제품을 거침없이 디스하는 컨텐츠로 인기가 치솟고있다.하지만 어느 순간 이상한 환청이 들리기 시작한다. 방송을 해야하는 시간은 다가오는데 증세는 더욱 심해진다. 이 상태로 방송을 진행할 것인가, 환청의 목소리를 따라 갈것인가.',
        '/image/엑스튜브.jpg'),
       ('완벽한미녀',
        '“아버지가 돌아오지 않아.. 무슨 일이 있는 건 아니겠지…”『진정한 행복이 무엇인지 나에게 깨달음을 준다면, 아버지를 돌려주겠습니다.』“나에게 진정한 행복을 가르쳐 주십시오. 그것만이 내 저주를 풀어낼 수 있습니다.”',
        '/image/완벽한미녀.png'),
       ('검은집',
        '일본 오사카 지역에서 모두가 동경하는 거대한 저택의 주인 부부가 알 수 없는 이유로 시체로 발견이 되었고, 첫째 딸과 둘째 딸 마저 차례대로 목숨을 잃은 채 발견 되었다. 어느 순간 사람들 사이에서 대저택이 악령의 저주를 받아 모두 살해 된 것이라는 소문이 돈다. 이유를 알 수 없는 화재까지 발생한 대저택. 과연 그 곳에선 어떤 일이 벌어지는 걸까? 당신은 내막을 밝히기 위해 대저택으로 향한다.',
        '/image/검은집.jpg'),
       ('게이트',
        '실종자들이 속출하기 시작했다. 지하수로에서 사라지는 사람들.. 출동한 경찰, 응급대원들도 모두 사라졌다. 정부는 수색작전에 동원하였지만 실종자들을 찾지 못했고 시간은 계속 흘러만 갔다. 결국 군사작전을 취소, 지하수로는 민간인 통제구역이 되었다. 정부는 입구주변을 둘러싸고 출입과 정보를 차단하였다. 하지만 이틀 전 지하수로에 들어간 기자와 전직군인들이 있었는데...',
        '/image/게이트.png'),
       ('501동 사람들',
        '1993년 부산의 목련아파트. 참사를 막기 위해 현재의 엑스파일러가 1993년 당일로 돌아가 비극을 막으려 한다. 왜, 무엇 때문에 그 일은 발생한 것인가! 과연 엑스파일러는 주민들을 구할 수 있을 것인가.',
        '/image/501동 사람들.png'),
       ('세번째밤',
        '압박감.긴장감.계속해서 반복되는 악몽에 나는 매일 밤 잠을 이루지 못한다. 그리고 오늘 꿈에 새로운 메세지가 나타나는데...',
        '/image/세번째밤.jpg'),
       ('육식주의자',
        '미국 플로리다주 마이애미, 여자들이 실종됐다. 오래된 정육점 근처에서 여자들의 비명소리를 들었다는 증언이 나오고 정육점 주인이 수사망에 오른다. 그러나 수사를 진행하던 요원들은 괴항의 습격으로 정신을 잃게 되는데-',
        '/image/육식주의자.jpg');

INSERT INTO reservation_time (start_at)
VALUES ('10:00'),
       ('12:00'),
       ('14:00'),
       ('16:00'),
       ('18:00');

INSERT INTO member(name, email, password, role)
VALUES ('테드', 'test1@email.com', '1450575459', 'USER'),
       ('종리', 'test2@email.com', '1450575459', 'USER'),
       ('범블비', 'test3@email.com', '1450575459', 'USER'),
       ('제이', 'test4@email.com', '1450575459', 'USER'),
       ('관리자', 'admin@email.com', '1450575459', 'ADMIN');

INSERT INTO reservation (date, time_id, theme_id, member_id, status)
VALUES (DATEADD('DAY', -1, CURRENT_DATE), 1, 1, 1, 'RESERVED'),
       (DATEADD('DAY', -3, CURRENT_DATE), 2, 1, 1, 'RESERVED'),
       (DATEADD('DAY', -7, CURRENT_DATE), 3, 1, 1, 'RESERVED'),
       (DATEADD('DAY', -1, CURRENT_DATE), 1, 2, 2, 'RESERVED'),
       (DATEADD('DAY', -3, CURRENT_DATE), 2, 2, 2, 'RESERVED'),
       (DATEADD('DAY', -7, CURRENT_DATE), 3, 3, 2, 'RESERVED'),
       (DATEADD('DAY', -1, CURRENT_DATE), 1, 3, 3, 'RESERVED'),
       (DATEADD('DAY', -3, CURRENT_DATE), 2, 4, 3, 'RESERVED'),
       (DATEADD('DAY', -7, CURRENT_DATE), 3, 5, 3, 'RESERVED'),
       (DATEADD('DAY', -1, CURRENT_DATE), 1, 6, 4, 'RESERVED'),
       (DATEADD('DAY', -2, CURRENT_DATE), 2, 7, 4, 'RESERVED'),
       (DATEADD('DAY', -3, CURRENT_DATE), 3, 8, 4, 'RESERVED'),
       (DATEADD('DAY', -4, CURRENT_DATE), 1, 9, 4, 'RESERVED'),
       (DATEADD('DAY', -5, CURRENT_DATE), 2, 10, 4, 'RESERVED'),
       (DATEADD('DAY', -7, CURRENT_DATE), 3, 11, 4, 'RESERVED'),
       (DATEADD('DAY', -8, CURRENT_DATE), 3, 12, 4, 'RESERVED'),
       (DATEADD('DAY', 1, CURRENT_DATE), 1, 1, 1, 'RESERVED'),
       (DATEADD('DAY', 1, CURRENT_DATE), 1, 1, 2, 'WAITING'),
       (DATEADD('DAY', 1, CURRENT_DATE), 1, 1, 3, 'WAITING'),
       (DATEADD('DAY', 1, CURRENT_DATE), 1, 1, 4, 'WAITING'),
       (DATEADD('DAY', 2, CURRENT_DATE), 1, 1, 1, 'RESERVED'),
       (DATEADD('DAY', 2, CURRENT_DATE), 1, 1, 2, 'WAITING');
