CREATE TABLE IF NOT EXISTS member (
    id       BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name     VARCHAR(255) NOT NULL,
    email     VARCHAR(255) NOT NULL UNIQUE,
    password  VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL CHECK (role IN ('USER','ADMIN')),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS reservation_time (
    id       BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    start_at TIME NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS theme (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255) NOT NULL,
    thumbnail   VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS reservation (
    id       BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    date     DATE NOT NULL,
    status VARCHAR(255) NOT NULL CHECK (status IN ('SUCCESS','CANCEL','WAIT')),
    member_id BIGINT NOT NULL,
    time_id  BIGINT NOT NULL,
    theme_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL default CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
