create table member
(
    id       bigint generated by default as identity,
    email    varchar(255) unique,
    name     varchar(255),
    password varchar(255),
    role     varchar(255) check (role in ('USER', 'ADMIN')),
    primary key (id)
);

create table payment
(
    amount         integer not null,
    approved_at    timestamp(6) with time zone,
    id             bigint generated by default as identity,
    requested_at   timestamp(6) with time zone,
    reservation_id bigint unique,
    order_id       varchar(255),
    order_name     varchar(255),
    payment_key    varchar(255),
    status         varchar(255) check (status in ('READY', 'IN_PROGRESS', 'WAITING_FOR_DEPOSIT', 'DONE', 'CANCELED',
                                                  'PARTIAL_CANCELED', 'ABORTED', 'EXPIRED')),
    primary key (id)
);

create table reservation
(
    date                date,
    id                  bigint generated by default as identity,
    member_id           bigint not null,
    reservation_time_id bigint not null,
    theme_id            bigint not null,
    status              varchar(255) check (status in ('BOOKED', 'PAYMENT_WAITING', 'CANCELED')),
    primary key (id)
);

create table reservation_time
(
    start_at time(6) unique,
    id       bigint generated by default as identity,
    primary key (id)
);

create table reservation_waiting
(
    id             bigint generated by default as identity,
    member_id      bigint not null,
    reservation_id bigint not null,
    primary key (id)
);

create table theme
(
    price       integer,
    id          bigint generated by default as identity,
    description varchar(255),
    name        varchar(255),
    thumbnail   varchar(255),
    primary key (id)
);

alter table if exists payment
    add constraint FK_ReservationPayment
        foreign key (reservation_id)
            references reservation;

alter table if exists reservation
    add constraint FK_ThemeReservation
        foreign key (theme_id)
            references theme;

alter table if exists reservation
    add constraint FK_ReservationTimeReservation
        foreign key (reservation_time_id)
            references reservation_time;

alter table if exists reservation
    add constraint FK_MemberReservation
        foreign key (member_id)
            references member;

alter table if exists reservation_waiting
    add constraint FK_MemberReservationWaiting
        foreign key (member_id)
            references member;

alter table if exists reservation_waiting
    add constraint FK_ReservationReservationWaiting
        foreign key (reservation_id)
            references reservation;

-- DROP TABLE IF EXISTS reservation_waiting;
-- DROP TABLE IF EXISTS payment;
-- DROP TABLE IF EXISTS reservation;
-- DROP TABLE IF EXISTS member;
-- DROP TABLE IF EXISTS reservation_time;
-- DROP TABLE IF EXISTS theme;