= 방탈출 API 명세
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 3
:sectlinks:
:sectnums:
:docinfo: shared-head

= v1.0.0
== 사용자
=== 로그인
==== 성공
operation::login/success[snippets='http-request,http-response']
==== 실패
|===
| 에러 코드 | 메시지 | 설명
| AUTH-004 | 비밀번호가 일치하지 않습니다. | 비밀번호가 다를 경우
|===

=== 로그인 사용 검증
==== 성공
operation::login/check/success[snippets='http-request,http-response']
==== 실패
|===
| 에러 코드 | 메시지 | 설명
| AUTH-002 | 유효하지 않은 토큰입니다. | 유효하지 않는 토큰일 경우
|===

=== 로그아웃
==== 성공
operation::logout/success[snippets='http-request,http-response']

=== 회원가입
==== 성공
operation::member/create/success[snippets='http-request,http-response']
==== 실패
|===
| 에러 코드 | 메시지 | 설명
| USER-003 | 중복된 이메일입니다. | 중복된 이메일일 경우
| USER-002 | 올바르지 않은 이메일 입력 양식입니다.| 이메일 형식이 잘못되었을 경우
| COMMON-003 | 올바르지 않은 데이터 요청입니다. | 비밀번호가 최소 8자 이상, 하나 이상의 대문자, 소문자, 숫자, 특수 문자를 포함하지 않을 경우
|===

== 예약
=== 예약 생성
==== 성공
operation::reservations/create/success[snippets='http-request,http-response']
==== 실패
|===
| 에러 코드 | 메시지 | 설명
| COMMON-003 | 올바르지 않은 데이터 요청입니다.| 지나간 날짜와 시간에 대한 예약 생성할 경우
|===

=== 예약 조회
==== 성공
operation::reservations/find/success[snippets='http-request,http-response']

=== 예약 삭제
==== 성공
operation::reservations/delete/success[snippets='http-request,http-response']
==== 실패
|===
| 에러 코드 | 메시지 | 설명
| RESERVATION-005 | 예약자가 아닙니다. | 타인의 예약 삭제할 경우
| COMMON-003 | 올바르지 않은 데이터 요청입니다." | 지나간 날짜와 시간에 대한 예약 생성할 경우
| RESERVATION-005 | 예약자가 아닙니다. | 타인의 예약 삭제할 경우
|===

=== 예약 대기 등록
==== 성공
operation::waiting/create/success[snippets='http-request,http-response']

=== 예약 대기 삭제
==== 성공
operation::waiting/delete/success[snippets='http-request,http-response']
==== 실패
|===
| 에러 코드 | 메시지 | 설명
| RESERVATION-005 | 예약자가 아닙니다. | 타인의 대기를 삭제할 경우
|===

== 예약 시간
=== 생성
==== 성공
operation::times/create/success[snippets='http-request,http-response']

=== 조회
==== 성공
operation::times/find/success[snippets='http-request,http-response']

=== 삭제
==== 성공
operation::times/delete/success[snippets='http-request,http-response']
==== 실패
|===
| 에러 코드 | 메시지 | 설명
| RESERVATION-004 | 예약이 존재하여 삭제할 수 없습니다. | 예약 시간을 갖는 예약이 존재하는 경우
|===

=== 가능한 시간 조회
==== 성공
operation::available-times/find/success[snippets='http-request,http-response']
==== 실패
|===
| 에러 코드 | 메시지 | 설명
| COMMON-003 | 올바르지 않은 데이터 요청입니다. | 조회하는 날짜가 과거인 경우
| THEME-001 | 해당 ID에 대응되는 테마가 없습니다. | 테마가 존재하지 않는 경우
|===

== 테마
=== 생성
==== 성공
operation::themes/create/success[snippets='http-request,http-response']
==== 실패
|===
| 에러 코드 | 메시지 | 설명
| COMMON-001 | 필수 요청값이 누락되었습니다. | 잘못된 테마 이름일 경우
|===

=== 조회
==== 성공
operation::themes/find/success[snippets='http-request,http-response']

=== 삭제
==== 성공
operation::themes/delete/success[snippets='http-request,http-response']
==== 실패
|===
| 에러 코드 | 메시지 | 설명
| RESERVATION-004 | 예약이 존재하여 삭제할 수 없습니다. | 테마를 갖는 예약이 존재하는 경우
| THEME-001 | 해당 ID에 대응되는 테마가 없습니다. | 존재하지 않는 테마를 삭제하는 경우
|===

=== 인기 테마 조회
==== 성공
operation::popular-themes/find/success[snippets='http-request,http-response']
==== 실패
|===
| 에러 코드 | 메시지 | 설명
| COMMON-003 | 올바르지 않은 데이터 요청입니다. | 1에서 20사이의 limit이 아닐 경우
|===

== 관리자
=== 예약 목록 조회
==== 성공
operation::admin-reservations/find/success[snippets='http-request,http-response']
==== 실패
|===
| 에러 코드 | 메시지 | 설명
| COMMON-003 | 올바르지 않은 데이터 요청입니다. | 존재하지 않는 매개변수
|===

=== 예약 생성
==== 성공
operation::admin-reservations/create/success[snippets='http-request,http-response']

=== 예약 삭제
==== 성공
operation::admin-reservations/delete/success[snippets='http-request,http-response']
==== 실패
|===
| 에러 코드 | 메시지 | 설명
| RESERVATION-003 | 해당 ID에 대응되는 사용자 예약이 없습니다. | 예약이 존재하지 않는 경우
|===

=== 예약 대기 승인
==== 성공
operation::approve/change/success[snippets='http-request,http-response']
==== 실패
|===
| 에러 코드 | 메시지 | 설명
| RESERVATION-006 | 대기 예약이 아닙니다. | 대기중인 예약이 아닌 경우
|===

=== 예약 대기 거절
==== 성공
operation::deny/change/success[snippets='http-request,http-response']
==== 실패
|===
| 에러 코드 | 메시지 | 설명
| RESERVATION-006 | 대기 예약이 아닙니다. | 대기중인 예약이 아닌 경우
|===

== 응답 형식
=== 성공 예시
[source,json]
----
HTTP/1.1 201 Created
Location: /times/2
Content-Type: application/json
Content-Length: 40
{
  "id" : 2,
  "startAt" : "12:00:00"
}
----

=== 에러 예시
[source,json]
----
HTTP/1.1 400 Bad Request
Content-Type: application/json
Content-Length: 100

{
  "code" : "RESERVATION-004",
  "message" : "예약이 존재하여 삭제할 수 없습니다."
}
----
=== 올바르지 않은 데이터 요청 에러 예시
[source,json]
----
HTTP/1.1 400 Bad Request
Content-Type: application/json
Content-Length: 214

{
  "errorCode" : "COMMON-003",
  "message" : "올바르지 않은 데이터 요청입니다.",
  "validation" : {
    "price" : "금액은 필수 값입니다.",
    "name" : "이름은 필수 값입니다."
  }
}
----
