= Room Escape API Documentation
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

== Introduction

This document describes the Room Escape API.

== Time Slot API

=== 예약 시간 추가
operation::time-slot/create[snippets='http-request,request-fields,http-response,response-fields']

=== 예약 시간 삭제
operation::time-slot/delete[snippets='http-request,path-parameters,http-response']

=== 예약 시간 목록 조회
operation::time-slot/find-all[snippets='http-request,http-response,response-fields']


== Theme API

=== 테마 생성
operation::theme/create[snippets='http-request,request-fields,http-response,response-fields']

=== 테마 삭제
operation::theme/delete[snippets='http-request,path-parameters,http-response']

=== 테마 목록 조회
operation::theme/find-all[snippets='http-request,http-response,response-fields']

=== 인기 테마 조회
operation::theme/find-all-popular[snippets='http-request,http-response,response-fields']


== Reservation API

=== 예약 목록 조회
operation::reservation/find-all[snippets='http-request,http-response,response-fields']

=== 예약 삭제
operation::reservation/delete[snippets='http-request,path-parameters,http-response']


== Admin Reservation API

=== 관리지 예약 생성
operation::admin-reservation/create-reservation[snippets='http-request,request-fields,http-response,response-fields']

=== 관리자 예약 조건 검색
operation::admin-reservation/filter-reservations[snippets='http-request,http-response,response-fields']

=== 관리자 예약 대기 목록 조회
operation::admin-reservation/find-all-waitings[snippets='http-request,http-response,response-fields']

=== 관리자 대기 삭제
operation::admin-reservation/delete-waiting[snippets='http-request,path-parameters,http-response']


== Member Reservation API

=== 멤버 예약 생성
operation::member-reservation/create-reservation[snippets='http-request,request-fields,http-response,response-fields']

=== 멤버 대기 생성
operation::member-reservation/create-waiting[snippets='http-request,request-fields,http-response,response-fields']

=== 멤버 대기 삭제
operation::member-reservation/delete-waiting[snippets='http-request,path-parameters,http-response']

=== 나의 예약/대기 목록 조회
operation::member-reservation/find-all-my-reservations[snippets='http-request,http-response,response-fields']


== Admin Login API

=== 관리자 로그인
operation::admin-login/login[snippets='http-request,request-fields,http-response,response-body']

=== 로그인 상태 확인
operation::admin-login/login-check[snippets='http-request,http-response,response-fields']


== Member Login API

=== 회원 로그인
operation::member-login/login[snippets='http-request,request-fields,http-response,response-body']

=== 로그인 상태 확인
operation::member-login/login-check[snippets='http-request,http-response,response-fields']
