= 방탈출 예약・관리 애플리케이션
:toc: left
:toclevels: 2
:toc-title: API 목록
:sectnums:
:source-highlighter: highlightjs

== 회원

=== 회원가입
operation::signup[snippets="http-request,request-fields,http-response,response-headers"]

=== 로그인
operation::login[snippets="http-request,http-response,response-cookies"]

=== 로그아웃
operation::logout[snippets="http-request,request-cookies,http-response,response-cookies"]

== 회원 예약

=== 예약 생성
operation::createReservationByUser[snippets="http-request,request-cookies,request-fields,http-response"]

=== 예약 취소
operation::cancelReservationByUser[snippets="http-request,request-cookies,path-parameters,http-response"]

=== 나의 예약 조회
operation::getMyReservation[snippets="http-request,request-cookies,http-response"]

== 회원 예약 대기

=== 예약 대기 생성
operation::createWaiting[snippets="http-request,request-cookies,request-fields,http-response"]

=== 예약 대기 삭제
operation::deleteWaiting[snippets="http-request,request-cookies,path-parameters,http-response"]

== 테마 조회

=== 인기 테마 조회
operation::getPopularThemes[snippets="http-request,query-parameters,http-response,response-fields"]

=== 모든 테마 목록 조회
operation::getEntireThemes[snippets="http-request,http-response,response-fields"]

== 예약 시간 조회

=== 전체 시간 목록 조회
operation::getEntireReservationTime[snippets="http-request,http-response,response-fields"]

=== 예약 가능한 시간 목록 조회
operation::getAvailableReservationTime[snippets="http-request,query-parameters,http-response,response-fields"]

== 관리자

=== 전체 회원 목록 조회
operation::getEntireMembers[snippets="http-request,http-response,response-fields"]

=== 전체 예약 조회
operation::getEntireReservations[snippets="http-request,http-response"]

=== 특정 예약 검색
operation::searchReservations[snippets="http-request,http-response"]

=== 전체 예약 대기 조회
operation::getEntireWaitings[snippets="http-request,http-response"]

=== 예약 생성
operation::createReservationByAdmin[snippets="http-request,request-cookies,request-fields,http-response"]

=== 예약 취소
operation::cancelReservationByAdmin[snippets="http-request,request-cookies,path-parameters,http-response"]

=== 예약 대기 삭제
operation::deleteWaitingByAdmin[snippets="http-request,request-cookies,path-parameters,http-response"]

== 테마 관리

=== 테마 생성
operation::createTheme[snippets="http-request,request-cookies,request-fields,http-response"]

=== 테마 삭제
operation::deleteTheme[snippets="http-request,request-cookies,path-parameters,http-response"]

== 시간 관리

=== 예약 시간 생성
operation::createReservationTime[snippets="http-request,request-cookies,request-fields,http-response"]

=== 예약 시간 삭제
operation::deleteReservationTime[snippets="http-request,request-cookies,path-parameters,http-response"]
