[[Reservation]]
= 1. 예약

== 1.1 회원 예약 저장

=== 성공

operation::reservations/save[snippets='http-request,http-response']

=== 실패

==== 이미 동일한 예약 내역을 가지고 있는 회원의 예약인 경우

operation::reservations/save/fail/duplicated[snippets='http-request,http-response']

==== 이미 예약되어 중복 예약이 불가능한 경우

operation::reservations/save/fail/already-reserved[snippets='http-request,http-response']

== 1.2 예약 전체 조회

=== 성공

operation::reservations/findAll[snippets='http-request,http-response']

== 1.3 내 예약 조회

=== 성공

operation::reservations/mine[snippets='http-request,http-response']

== 1.4 예약 검색

=== 성공

operation::reservations/search[snippets='http-request,http-response']

== 1.5 예약 제거

=== 성공

operation::reservations/delete[snippets='http-request,http-response']

== 1.6 관리자 예약 저장

=== 성공

operation::reservations/admin/save[snippets='http-request,http-response']

=== 실패

==== 이미 동일한 예약 내역을 가지고 있는 회원의 예약인 경우

operation::reservations/admin/save/fail/duplicated[snippets='http-request,http-response']

==== 이미 예약되어 중복 예약이 불가능한 경우

operation::reservations/admin/save/fail/already-reserved[snippets='http-request,http-response']
