=== 예약 대기 목록 조회 API (접근 권한: 관리자)

==== 200

operation::reservation-waiting-find-all-success[snippets="http-request,http-response,response-fields"]

=== 예약 대기 추가 API

==== 201

operation::reservation-waiting-save-success[snippets="http-request,request-fields,http-response,response-fields"]

==== 400

operation::reservation-waiting-save-bad-request[snippets="http-request,http-response"]

==== 404

operation::reservation-waiting-save-not-found[snippets="http-request,http-response"]

==== 409

operation::reservation-waiting-save-duplicate[snippets="http-request,http-response"]

=== 사용자 예약 대기 삭제 API

==== 204

operation::reservation-waiting-delete-success[snippets="http-request,path-parameters,http-response"]

==== 404

operation::reservation-waiting-delete-not-found[snippets="http-request,http-response"]

=== 관리자 예약 대기 삭제 API (접근 권한: 관리자)

==== 204

operation::reservation-waiting-admin-delete-success[snippets="http-request,path-parameters,http-response"]

==== 404

operation::reservation-waiting-admin-delete-not-found[snippets="http-request,http-response"]
