== 테마 API

=== 테마 생성

==== 테마 생성 성공

operation::theme-integration-test/create-theme[snippets='http-request,http-response']

==== 테마 생성 실패 - 테마 설명이 빈값

operation::theme-integration-test/create-theme_-when-theme-description-is-blank[snippets='http-request,http-response']

==== 테마 생성 실패 - 테마 설명이 글자 수 크기가 범위를 초과한 경우

operation::theme-integration-test/create-theme_-when-theme-name-is-blank[snippets='http-request,http-response']

==== 테마 생성 실패 - 테마 이름이 빈값

operation::theme-integration-test/create-theme_-when-theme-name-is-blank[snippets='http-request,http-response']

==== 테마 생성 실패 - 테마 설명이 글자 수 크기가 범위를 초과한 경우

operation::theme-integration-test/create-theme_-when-theme-name-over-length[snippets='http-request,http-response']

==== 테마 생성 실패 - 테마 썸네일이 빈값

operation::theme-integration-test/create-theme_-when-theme-thumbnail-is-blank[snippets='http-request,http-response']

==== 테마 생성 실패 - 테마 썸네일이 글자 수 크기가 범위를 초과한 경우

operation::theme-integration-test/create-theme_-when-theme-thumbnail-over-length[snippets='http-request,http-response']

=== 전체 테마 조회

==== 전체 테마 조회 성공

operation::theme-integration-test/get-themes[snippets='http-request,http-response']

=== 인기 테마 조회

==== 인기 테마 조회 성공

operation::theme-integration-test/get-popular-themes[snippets='http-request,http-response']

=== 테마 삭제

==== 테마 삭제 성공

operation::theme-integration-test/delete-theme[snippets='http-request,http-response']

==== 테마 삭제 실패 - 해당 테마인 예약이 존재하는 경우

operation::theme-integration-test/delete-theme_-when-theme-in-usage[snippets='http-request,http-response']

==== 테마 삭제 실패 - 존재하지 않는 테마

operation::theme-integration-test/delete-theme_-when-already-not-exist[snippets='http-request,http-response']
