package roomescape.global.exception.payment;

import static roomescape.global.exception.payment.TossPaymentErrorCode.ShowLevel.SENSITIVE;
import static roomescape.global.exception.payment.TossPaymentErrorCode.ShowLevel.SHOW_USER;
import static roomescape.global.exception.payment.TossPaymentErrorCode.ShowLevel.UNKNOWN;

import org.springframework.http.HttpStatus;

public enum TossPaymentErrorCode {

	ALREADY_PROCESSED_PAYMENT(HttpStatus.BAD_REQUEST, SHOW_USER),
	PROVIDER_ERROR(HttpStatus.BAD_REQUEST, SHOW_USER),
	EXCEED_MAX_CARD_INSTALLMENT_PLAN(HttpStatus.BAD_REQUEST, SHOW_USER),
	INVALID_REQUEST(HttpStatus.BAD_REQUEST, SHOW_USER),
	NOT_ALLOWED_POINT_USE(HttpStatus.BAD_REQUEST, SHOW_USER),

	INVALID_API_KEY(HttpStatus.BAD_REQUEST, SENSITIVE),
	INVALID_REJECT_CARD(HttpStatus.BAD_REQUEST, SHOW_USER),
	BELOW_MINIMUM_AMOUNT(HttpStatus.BAD_REQUEST, SHOW_USER),
	INVALID_CARD_EXPIRATION(HttpStatus.BAD_REQUEST, SHOW_USER),
	INVALID_STOPPED_CARD(HttpStatus.BAD_REQUEST, SHOW_USER),

	EXCEED_MAX_DAILY_PAYMENT_COUNT(HttpStatus.BAD_REQUEST, SHOW_USER),
	NOT_SUPPORTED_INSTALLMENT_PLAN_CARD_OR_MERCHANT(HttpStatus.BAD_REQUEST, SHOW_USER),
	INVALID_CARD_INSTALLMENT_PLAN(HttpStatus.BAD_REQUEST, SHOW_USER),
	NOT_SUPPORTED_MONTHLY_INSTALLMENT_PLAN(HttpStatus.BAD_REQUEST, SHOW_USER),
	EXCEED_MAX_PAYMENT_AMOUNT(HttpStatus.BAD_REQUEST, SHOW_USER),

	NOT_FOUND_TERMINAL_ID(HttpStatus.BAD_REQUEST, SHOW_USER),
	INVALID_AUTHORIZE_AUTH(HttpStatus.BAD_REQUEST, SHOW_USER),
	INVALID_CARD_LOST_OR_STOLEN(HttpStatus.BAD_REQUEST, SHOW_USER),
	RESTRICTED_TRANSFER_ACCOUNT(HttpStatus.BAD_REQUEST, SHOW_USER),
	INVALID_CARD_NUMBER(HttpStatus.BAD_REQUEST, SHOW_USER),

	INVALID_UNREGISTERED_SUBMALL(HttpStatus.BAD_REQUEST, SHOW_USER),
	NOT_REGISTERED_BUSINESS(HttpStatus.BAD_REQUEST, SHOW_USER),
	EXCEED_MAX_ONE_DAY_WITHDRAW_AMOUNT(HttpStatus.BAD_REQUEST, SHOW_USER),
	EXCEED_MAX_ONE_TIME_WITHDRAW_AMOUNT(HttpStatus.BAD_REQUEST, SHOW_USER),
	CARD_PROCESSING_ERROR(HttpStatus.BAD_REQUEST, SHOW_USER),

	EXCEED_MAX_AMOUNT(HttpStatus.BAD_REQUEST, SHOW_USER),
	INVALID_ACCOUNT_INFO_RE_REGISTER(HttpStatus.BAD_REQUEST, SHOW_USER),
	NOT_AVAILABLE_PAYMENT(HttpStatus.BAD_REQUEST, SHOW_USER),
	UNAPPROVED_ORDER_ID(HttpStatus.BAD_REQUEST, SENSITIVE),
	EXCEED_MAX_MONTHLY_PAYMENT_AMOUNT(HttpStatus.BAD_REQUEST, SHOW_USER),

	UNAUTHORIZED_KEY(HttpStatus.UNAUTHORIZED, SENSITIVE),
	REJECT_ACCOUNT_PAYMENT(HttpStatus.FORBIDDEN, SHOW_USER),
	REJECT_CARD_PAYMENT(HttpStatus.FORBIDDEN, SHOW_USER),
	REJECT_CARD_COMPANY(HttpStatus.FORBIDDEN, SHOW_USER),
	FORBIDDEN_REQUEST(HttpStatus.FORBIDDEN, SHOW_USER),

	REJECT_TOSSPAY_INVALID_ACCOUNT(HttpStatus.FORBIDDEN, SHOW_USER),
	EXCEED_MAX_AUTH_COUNT(HttpStatus.FORBIDDEN, SHOW_USER),
	EXCEED_MAX_ONE_DAY_AMOUNT(HttpStatus.FORBIDDEN, SHOW_USER),
	NOT_AVAILABLE_BANK(HttpStatus.FORBIDDEN, SHOW_USER),
	INVALID_PASSWORD(HttpStatus.FORBIDDEN, SHOW_USER),

	INCORRECT_BASIC_AUTH_FORMAT(HttpStatus.FORBIDDEN, SENSITIVE),
	FDS_ERROR(HttpStatus.FORBIDDEN, SHOW_USER),
	NOT_FOUND_PAYMENT(HttpStatus.NOT_FOUND, SHOW_USER),
	NOT_FOUND_PAYMENT_SESSION(HttpStatus.NOT_FOUND, SHOW_USER),
	FAILED_PAYMENT_INTERNAL_SYSTEM_PROCESSING(HttpStatus.INTERNAL_SERVER_ERROR, SHOW_USER),

	FAILED_INTERNAL_SYSTEM_PROCESSING(HttpStatus.INTERNAL_SERVER_ERROR, SHOW_USER),
	UNKNOWN_PAYMENT_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, SHOW_USER),

    UNKNOWN_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, UNKNOWN),
    ;

    public final HttpStatus httpStatus;
    public final ShowLevel level;

    TossPaymentErrorCode(HttpStatus httpStatus, ShowLevel level) {
        this.httpStatus = httpStatus;
        this.level = level;
    }

    public static TossPaymentErrorCode findTossPaymentErrorCode(String codeName) {
        for (TossPaymentErrorCode errorCode : values()) {
            if (errorCode.name().equals(codeName)) {
                return errorCode;
            }
        }
        return UNKNOWN_ERROR;
    }

    public enum ShowLevel {
        SHOW_USER,
        SENSITIVE,
        UNKNOWN
        ;
    }
}
