=== 예약 목록 조회
operation::admin-reservations/find/success[snippets='curl-request']
==== 성공
operation::admin-reservations/find/success[snippets='http-request,http-response']
==== 실패
|===
| 에러 코드 | 메시지 | 설명
| COMMON-003 | 올바르지 않은 데이터 요청입니다. | 존재하지 않는 매개변수
|===

=== 예약 생성
operation::admin-reservations/create/success[snippets='curl-request,request-fields']
==== 성공
operation::admin-reservations/create/success[snippets='http-request,http-response']

=== 예약 삭제
operation::admin-reservations/delete/success[snippets='curl-request']
==== 성공
operation::admin-reservations/delete/success[snippets='http-request,http-response']
==== 실패
|===
| 에러 코드 | 메시지 | 설명
| RESERVATION-003 | 해당 ID에 대응되는 사용자 예약이 없습니다. | 예약이 존재하지 않는 경우
|===

=== 예약 대기 승인
operation::approve/change/success[snippets='curl-request']
==== 성공
operation::approve/change/success[snippets='http-request,http-response']
==== 실패
|===
| 에러 코드 | 메시지 | 설명
| RESERVATION-006 | 대기 예약이 아닙니다. | 대기중인 예약이 아닌 경우
|===

=== 예약 대기 거절
operation::deny/change/success[snippets='curl-request']
==== 성공
operation::deny/change/success[snippets='http-request,http-response']
==== 실패
|===
| 에러 코드 | 메시지 | 설명
| RESERVATION-006 | 대기 예약이 아닙니다. | 대기중인 예약이 아닌 경우
|===
