DROP TABLE if exists waiting;
DROP TABLE if exists reservation;
DROP TABLE if exists theme;
DROP TABLE if exists time_slot;
DROP TABLE if exists member;

create table if not exists member (
    id bigint generated by default as identity,
    email varchar(255),
    name varchar(255),
    password varchar(255),
    role varchar(255) check (role in ('ADMIN','USER')),
    primary key (id)
);

create table if not exists reservation (
    date date,
    id bigint generated by default as identity,
    member_id bigint,
    theme_id bigint,
    time_id bigint,
    status varchar(255) check (status in ('BOOKING')),
    payment_key varchar(255),
    primary key (id)
);

create table if not exists theme (
    id bigint generated by default as identity,
    description varchar(255),
    name varchar(255),
    thumbnail varchar(255),
    price decimal,
    primary key (id)
);

create table if not exists time_slot (
    start_at time(6),
    id bigint generated by default as identity,
    primary key (id)
);

create table if not exists waiting (
    date date,
    id bigint generated by default as identity,
    member_id bigint,
    theme_id bigint,
    time_id bigint,
    status varchar(255) check (status in ('WAITING', 'PENDING')),
    primary key (id)
);

INSERT INTO time_slot(start_at)
VALUES ('00:00'),
       ('11:00'),
       ('12:00'),
       ('13:00');

INSERT INTO member(name, email, password, role)
VALUES ('어드민', 'testDB@email.com', '1234', 'ADMIN'),
       ('사용자', 'test2DB@email.com', '1234', 'USER');

INSERT INTO theme(name, description, thumbnail, price)
VALUES ('레벨1 탈출', '우테코 레벨2를 탈출하는 내용입니다.', 'https://i.pinimg.com/236x/6e/bc/46/6ebc461a94a49f9ea3b8bbe2204145d4.jpg', 10000),
       ('레벨2 탈출', '우테코 레벨3를 탈출하는 내용입니다.', 'https://i.pinimg.com/236x/6e/bc/46/6ebc461a94a49f9ea3b8bbe2204145d4.jpg', 15000),
       ('레벨3 탈출', '우테코 레벨4를 탈출하는 내용입니다.', 'https://i.pinimg.com/236x/6e/bc/46/6ebc461a94a49f9ea3b8bbe2204145d4.jpg', 20000);

INSERT INTO reservation(member_id, date, time_id, theme_id, status, payment_key)
VALUES (1, '2024-05-01', 1, 1, 'BOOKING', 'admin'),
       (1, '2024-05-24', 1, 1, 'BOOKING', 'admin'),
       (1, '2024-05-02', 1, 1, 'BOOKING', 'admin'),
       (2, '2024-05-26', 3, 3, 'BOOKING', 'admin'),
       (2, '2024-05-25', 3, 3, 'BOOKING', 'admin'),
       (2, '2024-06-09', 3, 3, 'BOOKING', 'admin'),
       (2, '2099-04-30', 1, 1, 'BOOKING', 'admin');

INSERT INTO waiting(member_id, date, time_id, theme_id, status)
VALUES (2, '2024-05-01', 1, 1, 'WAITING'),
       (2, '2024-05-02', 1, 1, 'WAITING'),
       (2, '2024-05-24', 1, 1, 'WAITING'),
       (1, '2024-05-24', 1, 1, 'WAITING'),
       (1, '2024-05-19', 3, 3, 'WAITING'),
       (1, '2024-05-18', 3, 3, 'WAITING'),
       (1, '2024-05-17', 3, 3, 'WAITING'),
       (2, '2099-05-30', 1, 1, 'PENDING');
