drop table if exists payment;
drop table if exists reservation;
drop table if exists reservation_time;
drop table if exists theme;
drop table if exists member;

create table member (
                        id bigint generated by default as identity,
                        email varchar(255) not null unique,
                        name varchar(255) not null,
                        password varchar(255) not null,
                        role varchar(255) not null check (role in ('USER','ADMIN')),
                        primary key (id)
);

create table theme (
                       id bigint generated by default as identity,
                       description varchar(255) not null,
                       name varchar(255) not null,
                       thumbnail varchar(255) not null,
                       primary key (id)
);

create table reservation_time (
                                  start_at time(6) not null,
                                  id bigint generated by default as identity,
                                  primary key (id)
);

create table reservation (
                             date date not null,
                             create_at timestamp(6) not null,
                             id bigint generated by default as identity,
                             member_id bigint not null,
                             theme_id bigint not null,
                             time_id bigint not null,
                             status varchar(255) not null check (status in ('BOOKED','STANDBY')),
                             primary key (id),
                             foreign key (member_id) references member(id),
                             foreign key (theme_id) references theme(id),
                             foreign key (time_id) references reservation_time(id)
);

create table payment (
                         amount bigint not null,
                         id bigint generated by default as identity,
                         reservation_id bigint not null unique,
                         order_id varchar(255) not null unique,
                         payment_key varchar(255) not null unique,
                         primary key (id),
                         foreign key (reservation_id) references reservation(id)
);
