DELETE
FROM payment;
DELETE
FROM canceled_payment;
DELETE
FROM reservation;
DELETE
FROM reservation_time;
DELETE
FROM theme;
DELETE
FROM member;

ALTER TABLE payment
    ALTER COLUMN id RESTART WITH 1;
ALTER TABLE canceled_payment
    ALTER COLUMN id RESTART WITH 1;
ALTER TABLE reservation
    ALTER COLUMN id RESTART WITH 1;
ALTER TABLE reservation_time
    ALTER COLUMN id RESTART WITH 1;
ALTER TABLE theme
    ALTER COLUMN id RESTART WITH 1;
ALTER TABLE member
    ALTER COLUMN id RESTART WITH 1;
